modLoader="javafml"
loaderVersion="[40,)"
license="Jacky's Minecraft Mods License"
issueTrackerURL="https://github.com/JackyyTV/GunpowderLib/issues"

[[mods]]
modId="gunpowderlib"
version="1.18.2-2.0"
displayName="GunpowderLib"
displayURL="https://github.com/JackyyTV/GunpowderLib"
logoFile="logo.png"
authors="Jackyy"
description='''
A support library for Jackyy's mods.
'''

[[dependencies.gunpowderlib]]
    modId="forge"
    mandatory=true
    versionRange="[40,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunpowderlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18,1.19)"
    ordering="NONE"
    side="BOTH"
