modLoader="javafml"
loaderVersion="[35,)"
license="LGPLv3"
issueTrackerURL="https://github.com/JackyyTV/GunpowderLib/issues"

[[mods]]
modId="gunpowderlib"
version="1.16.5-1.2.2"
displayName="GunpowderLib"
displayURL="https://github.com/JackyyTV/GunpowderLib"
logoFile="logo.png"
authors="Jackyy"
description='''
A support library for Jackyy's mods.
'''

[[dependencies.gunpowderlib]]
    modId="forge"
    mandatory=true
    versionRange="[35,)"
    ordering="NONE"
    side="BOTH"
[[dependencies.gunpowderlib]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16,1.17)"
    ordering="NONE"
    side="BOTH"
